export const fonts = [
    "Arial",
    "Time New Roman",
    "Abril Fatface",
    "Alegreya",
    "Archivo",
    "Arvo",
    "B612",
    "Bangers",
    "BioRhyme",
    "Bungee Shade",
    "Cairo",
    "Cardo",
    "Comic Neue",
    "Concert One",
    "Cormorant",
    "Crimson Text",
    "EB Garamond",
    "Exo 2",
    "Fira Sans",
    "Fjalla One",
    "Frank Ruhl Libre",
    "IBM Plex Serif",
    "Karla",
    "Lato",
    "Lora",
    "Merriweather",
    "Montserrat",
    "Noto Sans",
    "Nunito",
    "Old Standard TT",
    "Open Sans",
    "Oswald",
    "Oxygen",
    "Playfair Display",
    "Poppins",
    "PT Sans",
    "PT Serif",
    "Rakkas",
    "Roboto",
    "Rubik",
    "Rubik Mono One",
    "Ruluko",
    "Source Sans Pro",
    "Spectral",
    "Titillium Web",
    "Ubuntu",
    "Varela",
    "Vollkorn",
    "Work Sans",
    "Yatra One"
]